#+Title: Supervised Learning: \\ Building a Student Intervention System
#+AUTHOR: Robert M Salom
#+OPTIONS: toc:nil
* Obective 
The goal of this project is to identify students who might need early intervention. We want to predict whether a given student will pass or fail
based on information about his life and habits. Therefore we approach this task as a classification problem with two classes, pass and fail.

* Dataset
In what follows we will be working with part of the [[https://archive.ics.uci.edu/ml/datasets/student+performance][Student Performance Data Set]] from the UCI machine learning repository. It is composed of
395 data points with 30 attributes each. The 31'st attribute indicates whether the student passed or failed. Here is a brief description of
each feature:
** Attributes for student-data.csv:
 - school - student's school (binary: "GP" or "MS")
 - sex - student's sex (binary: "F" - female or "M" - male)
 - age - student's age (numeric: from 15 to 22)
 - address - student's home address type (binary: "U" - urban or "R" - rural)
 - famsize - family size (binary: "LE3" - less or equal to 3 or "GT3" - greater than 3)
 - Pstatus - parent's cohabitation status (binary: "T" - living together or "A" - apart)
 - Medu - mother's education (numeric: 0 - none, 1 - primary education (4th grade), 2 – 5th to 9th grade, 3 – secondary education or 4 – higher education)
 - Fedu - father's education (numeric: 0 - none, 1 - primary education (4th grade), 2 – 5th to 9th grade, 3 – secondary education or 4 – higher education)
 - Mjob - mother's job (nominal: "teacher", "health" care related, civil "services" (e.g. administrative or police), "at_home" or "other")
 - Fjob - father's job (nominal: "teacher", "health" care related, civil "services" (e.g. administrative or police), "at_home" or "other")
 - reason - reason to choose this school (nominal: close to "home", school "reputation", "course" preference or "other")
 - guardian - student's guardian (nominal: "mother", "father" or "other")
 - traveltime - home to school travel time (numeric: 1 - <15 min., 2 - 15 to 30 min., 3 - 30 min. to 1 hour, or 4 - >1 hour)
 - studytime - weekly study time (numeric: 1 - <2 hours, 2 - 2 to 5 hours, 3 - 5 to 10 hours, or 4 - >10 hours)
 - failures - number of past class failures (numeric: n if 1<=n<3, else 4)
 - schoolsup - extra educational support (binary: yes or no)
 - famsup - family educational support (binary: yes or no)
 - paid - extra paid classes within the course subject (Math or Portuguese) (binary: yes or no)
 - activities - extra-curricular activities (binary: yes or no)
 - nursery - attended nursery school (binary: yes or no)
 - higher - wants to take higher education (binary: yes or no)
 - internet - Internet access at home (binary: yes or no)
 - romantic - with a romantic relationship (binary: yes or no)
 - famrel - quality of family relationships (numeric: from 1 - very bad to 5 - excellent)
 - freetime - free time after school (numeric: from 1 - very low to 5 - very high)
 - goout - going out with friends (numeric: from 1 - very low to 5 - very high)
 - Dalc - workday alcohol consumption (numeric: from 1 - very low to 5 - very high)
 - Walc - weekend alcohol consumption (numeric: from 1 - very low to 5 - very high)
 - health - current health status (numeric: from 1 - very bad to 5 - very good)
 - absences - number of school absences (numeric: from 0 to 93)
 - passed - did the student pass the final exam (binary: yes or no)

** Reading the Data
#    #+BEGIN_SRC python 
#         # Import libraries
#         import numpy as np
#         import pandas as pd
#         import matplotlib.pyplot as plt
#    #+END_SRC

   #+name: f1
   #+BEGIN_SRC python :session tester
     def f1(x):
         return x * x
   #+END_SRC

   #+RESULTS: f1


   #+BEGIN_SRC python :session tester :results output
     print f1(9)
   #+END_SRC

   #+RESULTS:
   : 81


